# Closing The Case - ***Cleaning of Data***

## ***Data Import***

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [4]:
data = pd.read_csv(r"C:\Users\Rano's PC\Machine\InsightForge\InsightForge\Closing the Case\_raw_data\crime_dataset_india.csv",
                   encoding_errors='ignore')

In [5]:
data.head()

,Report Number,Date Reported,Date of Occurrence,Time of Occurrence,City,Crime Code,Crime Description,Victim Age,Victim Gender,Weapon Used,Crime Domain,Police Deployed,Case Closed,Date Case Closed
0,1,02-01-2020 00:00,01-01-2020 00:00,01-01-2020 01:11,Ahmedabad,576,IDENTITY THEFT,16,M,Blunt Object,Violent Crime,13,No,NaN
1,2,01-01-2020 19:00,01-01-2020 01:00,01-01-2020 06:26,Chennai,128,HOMICIDE,37,M,Poison,Other Crime,9,No,NaN
2,3,02-01-2020 05:00,01-01-2020 02:00,01-01-2020 14:30,Ludhiana,271,KIDNAPPING,48,F,Blunt Object,Other Crime,15,No,NaN
3,4,01-01-2020 05:00,01-01-2020 03:00,01-01-2020 14:46,Pune,170,BURGLARY,49,F,Firearm,Other Crime,1,Yes,29-04-2020 05:00
4,5,01-01-2020 21:00,01-01-2020 04:00,01-01-2020 16:51,Pune,421,VANDALISM,30,F,Other,Other Crime,18,Yes,08-01-2020 21:00

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40160 entries, 0 to 40159
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Report Number       40160 non-null  int64
 1   Date Reported       40160 non-null  object
 2   Date of Occurrence  40160 non-null  object
 3   Time of Occurrence  40160 non-null  object
 4   City                40160 non-null  object
 5   Crime Code          40160 non-null  int64
 6   Crime Description   40160 non-null  object
 7   Victim Age          40160 non-null  int64
 8   Victim Gender       40160 non-null  object
 9   Weapon Used         34370 non-null  object
 10  Crime Domain        40160 non-null  object
 11  Police Deployed     40160 non-null  int64
 12  Case Closed         40160 non-null  object
 13  Date Case Closed    20062 non-null  object
dtypes: int64(4), object(10)
memory usage: 4.3+ MB

In [9]:
data.describe(include='number')

       Report Number    Crime Code   Victim Age  Police Deployed
count   40160.000000  40160.000000  40160.00000     40160.000000
mean    20080.500000    349.360259     44.49126        10.006250
std     11593.337742    144.169205     20.22555         5.467951
min         1.000000    100.000000     10.00000         1.000000
25%     10040.750000    225.000000     27.00000         5.000000
50%     20080.500000    349.000000     44.00000        10.000000
75%     30120.250000    474.000000     62.00000        15.000000
max     40160.000000    599.000000     79.00000        19.000000

In [10]:
data.describe(include='object')

,Date Reported,Date of Occurrence,Time of Occurrence,City,Crime Description,Victim Gender,Weapon Used,Crime Domain,Case Closed,Date Case Closed
count,40160,40160,40160,40160,40160,40160,34370,40160,40160,20062
unique,25546,40160,39886,29,21,3,6,4,2,16011
top,24-12-2023 13:00,07-30-2024 15:00,14-10-2022 06:54,Delhi,BURGLARY,F,Knife,Other Crime,No,04-05-2024 18:00
freq,7,1,3,5400,1980,22423,5835,22948,20098,6

In [14]:
((data.isnull().sum()/len(data))*100).reset_index(name = 'null_pct').round(2)

                 index  null_pct
0        Report Number      0.00
1        Date Reported      0.00
2   Date of Occurrence      0.00
3   Time of Occurrence      0.00
4                 City      0.00
5           Crime Code      0.00
6    Crime Description      0.00
7           Victim Age      0.00
8        Victim Gender      0.00
9          Weapon Used     14.42
10        Crime Domain      0.00
11     Police Deployed      0.00
12         Case Closed      0.00
13    Date Case Closed     50.04

## Basic ***Data Preprocessing***

In [24]:
data.columns = data.columns.str.lower()

In [25]:
data.drop(columns="report number",inplace=True)

In [26]:
data.head()

,date reported,date of occurrence,time of occurrence,city,crime code,crime description,victim age,victim gender,weapon used,crime domain,police deployed,case closed,date case closed
0,02-01-2020 00:00,01-01-2020 00:00,01-01-2020 01:11,Ahmedabad,576,IDENTITY THEFT,16,M,Blunt Object,Violent Crime,13,No,NaN
1,01-01-2020 19:00,01-01-2020 01:00,01-01-2020 06:26,Chennai,128,HOMICIDE,37,M,Poison,Other Crime,9,No,NaN
2,02-01-2020 05:00,01-01-2020 02:00,01-01-2020 14:30,Ludhiana,271,KIDNAPPING,48,F,Blunt Object,Other Crime,15,No,NaN
3,01-01-2020 05:00,01-01-2020 03:00,01-01-2020 14:46,Pune,170,BURGLARY,49,F,Firearm,Other Crime,1,Yes,29-04-2020 05:00
4,01-01-2020 21:00,01-01-2020 04:00,01-01-2020 16:51,Pune,421,VANDALISM,30,F,Other,Other Crime,18,Yes,08-01-2020 21:00

In [33]:
rename_dict = {'date reported':'report_date','date of occurrence':'crime_date','time of occurrence':'crime_time','crime code':'crime_code',
               'crime description':'description',
               'victim age':'victim_age','victim gender':'victim_gender','weapon used':'weapon','crime domain':'crime_domain','police deployed':'police_deployed',
               'case closed':'case_close_status','date case closed':'close_date'}


data.rename(columns=rename_dict,inplace=True)

In [34]:
data.sample(5)

,report_date,crime_date,crime_time,city,crime_code,description,victim_age,victim_gender,weapon,crime_domain,police_deployed,case_close_status,close_date
35397,15-01-2024 01:00,01-14-2024 21:00,15-01-2024 19:48,Faridabad,293,ROBBERY,68,M,Poison,Violent Crime,11,Yes,23-02-2024 01:00
37055,24-03-2024 10:00,03-23-2024 23:00,24-03-2024 10:40,Delhi,312,SHOPLIFTING,35,F,Knife,Other Crime,18,Yes,11-06-2024 10:00
18198,29-01-2022 14:00,01-28-2022 06:00,28-01-2022 10:32,Kolkata,497,COUNTERFEITING,77,M,Poison,Other Crime,14,Yes,21-03-2022 14:00
14580,01-09-2021 04:00,08-30-2021 12:00,31-08-2021 09:59,Delhi,471,FIREARM OFFENSE,69,F,Explosives,Fire Accident,3,No,NaN
15889,25-10-2021 14:00,10-24-2021 01:00,24-10-2021 12:08,Chennai,264,ASSAULT,53,M,Firearm,Violent Crime,18,Yes,16-11-2021 14:00

In [42]:
data['report_date']=pd.to_datetime(data['report_date'],format='%d-%m-%Y %H:%M')

In [44]:
data['crime_date']=pd.to_datetime(data['crime_date'],format='%m-%d-%Y %H:%M')

In [45]:
data['crime_time']=pd.to_datetime(data['crime_time'],format='%d-%m-%Y %H:%M')

In [48]:
data['close_date']=pd.to_datetime(data['close_date'],format='%d-%m-%Y %H:%M')

In [49]:
data.head()

,report_date,crime_date,crime_time,city,crime_code,description,victim_age,victim_gender,weapon,crime_domain,police_deployed,case_close_status,close_date
0,2020-01-02 00:00:00,2020-01-01 00:00:00,2020-01-01 01:11:00,Ahmedabad,576,IDENTITY THEFT,16,M,Blunt Object,Violent Crime,13,No,NaT
1,2020-01-01 19:00:00,2020-01-01 01:00:00,2020-01-01 06:26:00,Chennai,128,HOMICIDE,37,M,Poison,Other Crime,9,No,NaT
2,2020-01-02 05:00:00,2020-01-01 02:00:00,2020-01-01 14:30:00,Ludhiana,271,KIDNAPPING,48,F,Blunt Object,Other Crime,15,No,NaT
3,2020-01-01 05:00:00,2020-01-01 03:00:00,2020-01-01 14:46:00,Pune,170,BURGLARY,49,F,Firearm,Other Crime,1,Yes,2020-04-29 05:00:00
4,2020-01-01 21:00:00,2020-01-01 04:00:00,2020-01-01 16:51:00,Pune,421,VANDALISM,30,F,Other,Other Crime,18,Yes,2020-01-08 21:00:00

In [50]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40160 entries, 0 to 40159
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   report_date        40160 non-null  datetime64[ns]
 1   crime_date         40160 non-null  datetime64[ns]
 2   crime_time         40160 non-null  datetime64[ns]
 3   city               40160 non-null  object
 4   crime_code         40160 non-null  int64
 5   description        40160 non-null  object
 6   victim_age         40160 non-null  int64
 7   victim_gender      40160 non-null  object
 8   weapon             34370 non-null  object
 9   crime_domain       40160 non-null  object
 10  police_deployed    40160 non-null  int64
 11  case_close_status  40160 non-null  object
 12  close_date         20062 non-null  datetime64[ns]
dtypes: datetime64[ns](4), int64(3), object(6)
memory usage: 4.0+ MB

## ***Numerical*** Columns

**Crime Code**

In [55]:
data['crime_code'].describe().reset_index().T

                  0           1           2      3      4      5      6      7
index         count        mean         std    min    25%    50%    75%    max
crime_code  40160.0  349.360259  144.169205  100.0  225.0  349.0  474.0  599.0

In [56]:
data['crime_code'].nunique()

500

``` crime code is numerical column, but it does not have any numerical value impact, and as a categorical column, it have too many uniquq values and will not have a good impact on analysis, so dropping the column will be the best idea ```

**Victim Age**

In [57]:
data['victim_age'].describe()

count    40160.00000
mean        44.49126
std         20.22555
min         10.00000
25%         27.00000
50%         44.00000
75%         62.00000
max         79.00000
Name: victim_age, dtype: float64

**Police Deployed**

In [58]:
data['police_deployed'].describe()

count    40160.000000
mean        10.006250
std          5.467951
min          1.000000
25%          5.000000
50%         10.000000
75%         15.000000
max         19.000000
Name: police_deployed, dtype: float64

## ***Categorical*** Columns

**City**

In [59]:
data['city'].value_counts()

city
Delhi            5400
Mumbai           4415
Bangalore        3588
Hyderabad        2881
Kolkata          2518
Chennai          2493
Pune             2212
Ahmedabad        1817
Jaipur           1479
Lucknow          1456
Kanpur           1112
Surat            1111
Nagpur           1053
Agra              764
Ludhiana          761
Visakhapatnam     728
Thane             706
Ghaziabad         704
Indore            699
Patna             695
Bhopal            690
Meerut            395
Srinagar          371
Nashik            366
Vasai             362
Varanasi          355
Kalyan            355
Faridabad         354
Rajkot            320
Name: count, dtype: int64

In [61]:
data['city']=data['city'].apply(lambda x: x.lower())

In [63]:
data['city'].sample(5)

30535     kolkata
13043    varanasi
38959      indore
26570        pune
10639       delhi
Name: city, dtype: object

**Gender**

In [65]:
data['victim_gender'].value_counts()

victim_gender
F    22423
M    13405
X     4332
Name: count, dtype: int64

In [67]:
gender_dict ={
    'F':'Female',
    'M':'Male',
    'X':'Unknown'
}


data['victim_gender']=data['victim_gender'].map(gender_dict)

In [68]:
data['victim_gender'].value_counts()

victim_gender
Female     22423
Male       13405
Unknown     4332
Name: count, dtype: int64

**Description**

In [69]:
data['description'].value_counts()

description
BURGLARY               1980
VANDALISM              1975
FRAUD                  1965
DOMESTIC VIOLENCE      1932
FIREARM OFFENSE        1931
ROBBERY                1928
KIDNAPPING             1920
IDENTITY THEFT         1918
SEXUAL ASSAULT         1917
ASSAULT                1915
TRAFFIC VIOLATION      1915
PUBLIC INTOXICATION    1912
HOMICIDE               1909
CYBERCRIME             1899
ILLEGAL POSSESSION     1895
ARSON                  1894
DRUG OFFENSE           1890
EXTORTION              1873
COUNTERFEITING         1871
VEHICLE - STOLEN       1862
SHOPLIFTING            1859
Name: count, dtype: int64

In [81]:
data['description']=data['description'].apply(lambda x: x.title())

In [82]:
data.loc[data['description']=='vehicle - stolen', 'description'] = 'stolen vehicle'

**Weapon**

In [80]:
data['weapon'].value_counts()

weapon
Knife           5835
Explosives      5751
Blunt Object    5737
Poison          5728
Other           5676
Firearm         5643
Name: count, dtype: int64

## ***Feature*** Engineering