# ```Initial Preparation of IPO Datasets```

In [1]:
import pandas as pd
import numpy as np

In [2]:
prices = pd.read_csv(r"C:\Users\Rano's PC\Machine\InsightForge\InsightForge\Avoiding The Hype Trap\_datasets\_raw\price_history_raw.csv")


info = pd.read_csv(r"C:\Users\Rano's PC\Machine\InsightForge\InsightForge\Avoiding The Hype Trap\_datasets\_raw\ipo_performance_raw.csv")

In [3]:
prices.head()

,Company,Ticker,Date,Open,High,Low,Close,Volume
0,Prince Pipes & Fittings Ltd.,PRINCEPIPE.NS,30-12-2019,160.000000,177.899994,152.500000,166.899994,21159947
1,Prince Pipes & Fittings Ltd.,PRINCEPIPE.NS,31-12-2019,162.300003,167.399994,150.600006,152.449997,5939748
2,Prince Pipes & Fittings Ltd.,PRINCEPIPE.NS,01-01-2020,153.050003,159.500000,152.399994,155.850006,3114230
3,Prince Pipes & Fittings Ltd.,PRINCEPIPE.NS,02-01-2020,156.050003,158.699997,154.000000,155.699997,1021302
4,Prince Pipes & Fittings Ltd.,PRINCEPIPE.NS,03-01-2020,156.000000,156.000000,151.250000,151.899994,623408

In [4]:
prices.drop(columns="Ticker",inplace=True)

In [5]:
prices.head()

,Company,Date,Open,High,Low,Close,Volume
0,Prince Pipes & Fittings Ltd.,30-12-2019,160.000000,177.899994,152.500000,166.899994,21159947
1,Prince Pipes & Fittings Ltd.,31-12-2019,162.300003,167.399994,150.600006,152.449997,5939748
2,Prince Pipes & Fittings Ltd.,01-01-2020,153.050003,159.500000,152.399994,155.850006,3114230
3,Prince Pipes & Fittings Ltd.,02-01-2020,156.050003,158.699997,154.000000,155.699997,1021302
4,Prince Pipes & Fittings Ltd.,03-01-2020,156.000000,156.000000,151.250000,151.899994,623408

In [6]:
prices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266370 entries, 0 to 266369
Data columns (total 7 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   Company  266370 non-null  object
 1   Date     266370 non-null  object
 2   Open     266370 non-null  float64
 3   High     266370 non-null  float64
 4   Low      266370 non-null  float64
 5   Close    265992 non-null  float64
 6   Volume   266370 non-null  int64
dtypes: float64(4), int64(1), object(2)
memory usage: 14.2+ MB

In [7]:
prices['Date']=pd.to_datetime(prices['Date'], format='%d-%m-%Y')

In [8]:
prices.columns = prices.columns.str.lower()

In [9]:
prices[['open','high','low','close']] = prices[['open','high','low','close']].round(2)

In [10]:
prices.head()

,company,date,open,high,low,close,volume
0,Prince Pipes & Fittings Ltd.,2019-12-30,160.00,177.9,152.50,166.90,21159947
1,Prince Pipes & Fittings Ltd.,2019-12-31,162.30,167.4,150.60,152.45,5939748
2,Prince Pipes & Fittings Ltd.,2020-01-01,153.05,159.5,152.40,155.85,3114230
3,Prince Pipes & Fittings Ltd.,2020-01-02,156.05,158.7,154.00,155.70,1021302
4,Prince Pipes & Fittings Ltd.,2020-01-03,156.00,156.0,151.25,151.90,623408

In [11]:
info.head()

,ipo_company_name,ipo_issue_type,ipo_issue_price_final,il_ipo_listing_date,il_bse_script_code,il_nse_script_symbol,ipo_issue_size_in_amt,change_in_percentage_listing_day,ipo_profit_loss,ildt_open_price,ildt_close_price,ildt_high_price,ildt_low_price,qib,nii,rii,emp,total,last_modified_date,Year
0,Prince Pipes & Fittings Ltd.,IPO,178,2019-12-30T00:00:00.000Z,542907.0,PRINCEPIPE,5.000000e+09,-6.24,50.06,160.00,166.90,177.9,152.50,2.02,0.52,1.63,NaN,1.66,14-07-2026,2019
1,Manaksia Ltd.,FPO,160,2019-12-26T00:00:00.000Z,NaN,NaN,2.480000e+09,4.81,0.00,175.30,167.70,212.0,161.70,13.70,1.51,4.67,0.49,8.66,14-07-2026,2019
2,Ujjivan Small Finance Bank Ltd.,IPO,37,2019-12-12T00:00:00.000Z,542904.0,UJJIVANSFB,7.459459e+09,51.22,76.08,58.75,55.95,62.8,53.05,46.30,473.33,45.29,NaN,99.61,14-07-2026,2019
3,CSB Bank Ltd.,IPO,195,2019-12-04T00:00:00.000Z,542867.0,CSBBANK,4.096768e+09,53.87,82.69,275.00,300.05,306.8,275.00,25.52,164.27,40.98,NaN,47.88,14-07-2026,2019
4,Precision Pipes & Profiles Co.Ltd.,IPO,150,2019-12-02T00:00:00.000Z,NaN,NaN,7.500000e+08,-9.27,0.00,165.00,136.10,175.0,132.00,5.39,8.26,19.02,NaN,10.59,14-07-2026,2019

In [17]:
prices['company'].nunique()

379

In [12]:
info.columns

Index(['ipo_company_name', 'ipo_issue_type', 'ipo_issue_price_final',
       'il_ipo_listing_date', 'il_bse_script_code', 'il_nse_script_symbol',
       'ipo_issue_size_in_amt', 'change_in_percentage_listing_day',
       'ipo_profit_loss', 'ildt_open_price', 'ildt_close_price',
       'ildt_high_price', 'ildt_low_price', 'qib', 'nii', 'rii', 'emp',
       'total', 'last_modified_date', 'Year'],
      dtype='object')

In [13]:
ipo = info[['ipo_company_name', 'ipo_issue_type', 'il_ipo_listing_date', 'ipo_issue_price_final', 'change_in_percentage_listing_day', 'rii']]

In [14]:
ipo.head()

,ipo_company_name,ipo_issue_type,il_ipo_listing_date,ipo_issue_price_final,change_in_percentage_listing_day,rii
0,Prince Pipes & Fittings Ltd.,IPO,2019-12-30T00:00:00.000Z,178,-6.24,1.63
1,Manaksia Ltd.,FPO,2019-12-26T00:00:00.000Z,160,4.81,4.67
2,Ujjivan Small Finance Bank Ltd.,IPO,2019-12-12T00:00:00.000Z,37,51.22,45.29
3,CSB Bank Ltd.,IPO,2019-12-04T00:00:00.000Z,195,53.87,40.98
4,Precision Pipes & Profiles Co.Ltd.,IPO,2019-12-02T00:00:00.000Z,150,-9.27,19.02

In [15]:
ipo[ipo['ipo_issue_type']  =='IPO']

,ipo_company_name,ipo_issue_type,il_ipo_listing_date,ipo_issue_price_final,change_in_percentage_listing_day,rii
0,Prince Pipes & Fittings Ltd.,IPO,2019-12-30T00:00:00.000Z,178,-6.24,1.63
2,Ujjivan Small Finance Bank Ltd.,IPO,2019-12-12T00:00:00.000Z,37,51.22,45.29
3,CSB Bank Ltd.,IPO,2019-12-04T00:00:00.000Z,195,53.87,40.98
4,Precision Pipes & Profiles Co.Ltd.,IPO,2019-12-02T00:00:00.000Z,150,-9.27,19.02
5,Vishwaraj Sugar Industries Ltd.,IPO,2019-10-15T00:00:00.000Z,60,0.58,0.59
...,...,...,...,...,...,...
396,Stallion India Fluorochemicals Ltd.,IPO,2025-01-23T00:00:00.000Z,90,40.00,94.51
397,Laxmi Dental Ltd.,IPO,2025-01-20T00:00:00.000Z,428,28.63,75.35
399,Quadrant Future Tek Ltd.,IPO,2025-01-14T00:00:00.000Z,290,53.10,256.63
400,Standard Glass Lining Technology Ltd.,IPO,2025-01-13T00:00:00.000Z,140,16.68,65.72
401,Indo Farm Equipment Ltd.,IPO,2025-01-07T00:00:00.000Z,215,27.30,102.57

In [19]:
common_companies = set(ipo['ipo_company_name']) & set(prices['company'])

ipo = ipo[ipo['ipo_company_name'].isin(common_companies)].reset_index(drop=True)
prices= prices[prices['company'].isin(common_companies)].reset_index(drop=True)

In [20]:
ipo.head()

,ipo_company_name,ipo_issue_type,il_ipo_listing_date,ipo_issue_price_final,change_in_percentage_listing_day,rii
0,Prince Pipes & Fittings Ltd.,IPO,2019-12-30T00:00:00.000Z,178,-6.24,1.63
1,Ujjivan Small Finance Bank Ltd.,IPO,2019-12-12T00:00:00.000Z,37,51.22,45.29
2,CSB Bank Ltd.,IPO,2019-12-04T00:00:00.000Z,195,53.87,40.98
3,Vishwaraj Sugar Industries Ltd.,IPO,2019-10-15T00:00:00.000Z,60,0.58,0.59
4,Indian Railway Catering & Tourism Corp.Ltd.,IPO,2019-10-14T00:00:00.000Z,320,127.42,13.28

In [25]:
ipo['ipo_company_name'].nunique()

379

In [26]:
prices['company'].nunique()

379

In [27]:
ipo.drop(columns='ipo_issue_type',inplace=True)

In [30]:
rename_dict = {
    'ipo_company_name':'company',
    'il_ipo_listing_date':'listing_date',
    'ipo_issue_price_final':'final_price',
    'change_in_percentage_listing_day':'price_change',
    'rii':'retail_subscription '
}


ipo.rename(columns=rename_dict,inplace=True)

In [31]:
ipo.head()

,company,listing_date,final_price,price_change,retail_subscription
0,Prince Pipes & Fittings Ltd.,2019-12-30T00:00:00.000Z,178,-6.24,1.63
1,Ujjivan Small Finance Bank Ltd.,2019-12-12T00:00:00.000Z,37,51.22,45.29
2,CSB Bank Ltd.,2019-12-04T00:00:00.000Z,195,53.87,40.98
3,Vishwaraj Sugar Industries Ltd.,2019-10-15T00:00:00.000Z,60,0.58,0.59
4,Indian Railway Catering & Tourism Corp.Ltd.,2019-10-14T00:00:00.000Z,320,127.42,13.28

In [34]:
ipo['listing_date']=pd.to_datetime(ipo['listing_date']).dt.date

In [35]:
ipo.head()

,company,listing_date,final_price,price_change,retail_subscription
0,Prince Pipes & Fittings Ltd.,2019-12-30,178,-6.24,1.63
1,Ujjivan Small Finance Bank Ltd.,2019-12-12,37,51.22,45.29
2,CSB Bank Ltd.,2019-12-04,195,53.87,40.98
3,Vishwaraj Sugar Industries Ltd.,2019-10-15,60,0.58,0.59
4,Indian Railway Catering & Tourism Corp.Ltd.,2019-10-14,320,127.42,13.28

In [37]:
prices.head()

,company,date,open,high,low,close,volume
0,Prince Pipes & Fittings Ltd.,2019-12-30,160.00,177.9,152.50,166.90,21159947
1,Prince Pipes & Fittings Ltd.,2019-12-31,162.30,167.4,150.60,152.45,5939748
2,Prince Pipes & Fittings Ltd.,2020-01-01,153.05,159.5,152.40,155.85,3114230
3,Prince Pipes & Fittings Ltd.,2020-01-02,156.05,158.7,154.00,155.70,1021302
4,Prince Pipes & Fittings Ltd.,2020-01-03,156.00,156.0,151.25,151.90,623408

In [39]:
ipo.to_csv(r"C:\Users\Rano's PC\Machine\InsightForge\InsightForge\Avoiding The Hype Trap\_datasets\_cleaned\ipo.csv",index=False)

prices.to_csv(r"C:\Users\Rano's PC\Machine\InsightForge\InsightForge\Avoiding The Hype Trap\_datasets\_cleaned\prices.csv",index=False)